

#GPS RAW
lattitude_ref: 45
longitude_ref: 12

lattitude_cov: 1
longitude_cov: 1
gps_rate: 3

#Position Config
position_x_cov: 1
position_y_cov: 1
position_z_cov: 0.5
position_rate: 10

#Velocity Config
velocity_x_cov: 0.2
velocity_y_cov: 0.2
velocity_z_cov: 0.1
velocity_rate: 10

# Euler Angles Config
filtered_euler_x_cov: 0.01
filtered_euler_y_cov: 0.01
filtered_euler_z_cov: 0.01
filtered_accel_x_cov: 0.01
filtered_accel_y_cov: 0.01
filtered_accel_z_cov: 0.01
filtered_gyro_x_cov: 0.01
filtered_gyro_y_cov: 0.01
filtered_gyro_z_cov: 0.01
attitude_filter_rate: 100

# Accelerometer Config
accel_x_cov: 0.01
accel_y_cov: 0.01
accel_z_cov: 0.01
accelerometer_raw_rate: 200

# Gyro Config
gyro_x_cov: 0.01
gyro_y_cov: 0.01
gyro_z_cov: 0.01
gyroscope_raw_rate: 200

# Magnetometer Config
mag_x_cov: 0.01
mag_y_cov: 0.01
mag_z_cov: 0.01
magnetometer_raw_rate: 20

# Barometer Config
pressure_cov: 0.01
barometer_raw_rate: 20



