# Altitude PID Message for logging
# For Ciconia - Hybrid VTOL Aircraft.

Header header

float64 time

float64 reference_altitude
float64 altitude
float64 home_altitude
float64 velocity_signal
float64 velocity
float64 acceleration_signal
float64 acceleration
float64 throttle
float64 reference_throttle

float64 alt_to_vel_p
float64 alt_to_vel_i
float64 alt_to_vel_d

float64 vel_to_acc_p
float64 vel_to_acc_i
float64 vel_to_acc_d

float64 acc_to_thrust_p
float64 acc_to_thrust_i
float64 acc_to_thrust_d
