# Sbus RC Messages
# For Ciconia - Hybrid VTOL Aircraft.

Header header 

uint16 channel0
uint16 channel1
uint16 channel2
uint16 channel3
uint16 channel4
uint16 channel5
uint16 channel6
uint16 channel7
uint16 channel8
uint16 channel9
uint16 channel10
uint16 channel11
uint16 channel12
uint16 channel13
uint16 channel14
uint16 channel15

uint8  channel17
uint8  channel18
uint8  lostframe
uint8  failsafe
